version: '3.8'
services:
  ocr:
    build: .
    volumes:
      - ./documents:/app/documents
      - ./output_text:/app/output_text
    command: python OllamaTest.py

  parser:
    build: .
    volumes:
      - ./output_text:/app/output_text
      - ./output_json:/app/output_json
    command: python send_to_ollama.py