version: '3.8'
services:
  extractor:
    build: .
    volumes:
      - ./receipt_images:/app/receipt_images
      - ./output_json:/app/output_json
      - ./processed_images:/app/processed_images
    command: python image-json-converter.py
    environment:
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}

  categorizer:
    build: .
    volumes:
      - ./output_json:/app/output_json
    command: python prod_cat_cloud.py
    environment:
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}